#re-write LocalDBLocation
#Sun Mar 28 13:23:49 JST 2021

UseDefaultLocalDBLocation=true
MainTreeTableKeepTopTitle=HOME
RefreshQRTreeTableOn=true
IgnoreNullSearchKeyWarning=false
FontSize=12
ColumnOrder=
LocalDBLocation=
LookAndFeels=
NumOfPadForPatientID=0
TextFont=12
Xms=1g
Xmx=10g
NO_SPLASH=false
# C-GET or C-MOVE
DIMSE_CGET_CMOVE=CGET
