<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.vis.graphy</groupId>
	<artifactId>graphy</artifactId>
	<version>0.0.17</version>
	
	<licenses>
		<license>
			<name> Mozilla Public License, Version 2.0 </name>
	    	<url>https://opensource.org/licenses/MPL-2.0</url>
	  	</license>
	</licenses>
	
	<developers>
		<developer>
      		<name>Tatsuaki Kobayashi</name>
      		<email>t_kobayashi@vis-ionary.com</email>
      		<organization>Visionry Imaging Services, Inc.</organization>
      		<organizationUrl>https://www.vis-ionary.com</organizationUrl>
    	</developer>
	</developers>

	<properties>
		<exec.mainClass>com.vis.core.launcher.Launcher</exec.mainClass>
		<java.version>11</java.version>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
		<maven.compiler.release>11</maven.compiler.release>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<radiomicsj-version>2.1.18</radiomicsj-version>
		<dcm4che-version>5.23.2</dcm4che-version>
		<derby-version>10.13.1.1</derby-version>
		<pdfbox-version>2.0.24</pdfbox-version>
		<apache-commons-io-version>2.14.0</apache-commons-io-version>
		<radiance-substance-version>4.5.0</radiance-substance-version>
		<joml-version>1.10.5</joml-version>
		<asm-version>9.5</asm-version>
		<weka-version>3.9.6</weka-version>
		<!-- USE 3.3.6 to keep compatible with lwjgl3-awt 0.2.3 -->
		<lwjgl.version>3.3.6</lwjgl.version>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<release>${java.version}</release>
				</configuration>
			</plugin>
			<!-- Set above from assembly plugin -->
			<plugin>
			    <groupId>org.apache.maven.plugins</groupId>
			    <artifactId>maven-dependency-plugin</artifactId>
			    <version>3.6.0</version> <executions>
			        <execution>
			            <id>copy-dependencies</id>
			            <phase>package</phase>
			            <goals>
			                <goal>copy-dependencies</goal>
			            </goals>
			            <configuration>
			                <outputDirectory>${project.build.directory}/jars</outputDirectory> <overWriteReleases>false</overWriteReleases>
			                <overWriteSnapshots>false</overWriteSnapshots>
			                <overWriteIfNewer>true</overWriteIfNewer>
			            </configuration>
			        </execution>
			    </executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.4.2</version>
				<configuration>
					<archive>
						<manifest>
							<addClasspath>true</addClasspath>
							<mainClass>com.vis.core.launcher.Launcher</mainClass>
							<classpathPrefix>./jars/</classpathPrefix>
						</manifest>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>3.6.0</version>
				<executions>
					<execution>
						<id>make-windows-dist</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
						<configuration>
							<descriptors>
								<descriptor>src/main/assembly/windows.xml</descriptor>
							</descriptors>
							<finalName>GRAPHY-${project.version}-Windows</finalName>
							<appendAssemblyId>false</appendAssemblyId>
						</configuration>
					</execution>
					<execution>
						<id>make-linux-dist</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
						<configuration>
							<descriptors>
								<descriptor>src/main/assembly/linux.xml</descriptor>
							</descriptors>
							<finalName>GRAPHY-${project.version}-Ubuntu</finalName>
							<appendAssemblyId>false</appendAssemblyId>
						</configuration>
					</execution>
					<execution>
						<id>make-mac-dist</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
						<configuration>
							<descriptors>
								<descriptor>src/main/assembly/mac.xml</descriptor>
							</descriptors>
							<finalName>GRAPHY-${project.version}-Mac</finalName>
							<appendAssemblyId>false</appendAssemblyId>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
		<resources>
		<!-- for application.properties -->
       	<resource>
          		<directory>src/main/resources</directory>
            	<filtering>true</filtering>
            	<includes>
                	<include>**/*.properties</include>
            	</includes>
        	</resource>
	        <!-- others -->
    	   	<resource>
          		<directory>src/main/resources</directory>
            	<filtering>false</filtering>
            	<includes>
              	<include>**/*</include> <!-- all files -->
            	</includes>
            	<excludes>
              	<exclude>**/*.properties</exclude>
            	</excludes>
        	</resource>
		</resources>
	</build>

	<repositories>
		<!-- pixelmed.jar -->
		<repository>
			<id>XNatLibs</id>
			<name>XNatLibs Repository</name>
			<url>https://nrgxnat.jfrog.io/artifactory/libs-release/</url>
		</repository>
		<!-- dcm4che -->
		<repository>
			<id>SciJava Public</id>
			<name>SciJava Public Repository</name>
			<url>https://maven.scijava.org/content/repositories/public/</url>
		</repository>
		<repository>
			<id>Dcm4Che</id>
			<name>Dcm4Che Repository</name>
			<url>https://www.dcm4che.org/maven2/</url>
		</repository>
		<!-- dcm4che imageio opencv -->
		<repository>
			<id>weasis-github-repo</id>
			<name>Weasis GitHub Repository</name>
			<url>https://raw.githubusercontent.com/nroduit/mvn-repo/master/</url>
		</repository>
	</repositories>

	<dependencies>
		<dependency>
		    <groupId>io.github.tatsunidas</groupId>
		    <artifactId>radiomicsj</artifactId>
		    <version>${radiomicsj-version}</version>
		</dependency>
		<!-- DB LIBRARIES -->

		<!-- https://mvnrepository.com/artifact/org.apache.derby/derby -->
		<dependency>
			<groupId>org.apache.derby</groupId>
			<artifactId>derby</artifactId>
			<version>${derby-version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.apache.derby/derbyclient -->
		<dependency>
			<groupId>org.apache.derby</groupId>
			<artifactId>derbyclient</artifactId>
			<version>${derby-version}</version>
		</dependency>

		<!-- DICOM LIBRARIES -->

		<dependency>
			<groupId>org.dcm4che</groupId>
			<artifactId>dcm4che-core</artifactId>
			<version>${dcm4che-version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.dcm4che/dcm4che-imageio-rle -->
		<dependency>
			<groupId>org.dcm4che</groupId>
			<artifactId>dcm4che-imageio-rle</artifactId>
			<version>${dcm4che-version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.dcm4che/dcm4che-imageio -->
		<dependency>
			<groupId>org.dcm4che</groupId>
			<artifactId>dcm4che-imageio</artifactId>
			<version>${dcm4che-version}</version>
		</dependency>
		<dependency>
			<groupId>com.sun.media</groupId>
			<artifactId>jai_imageio</artifactId>
			<version>1.2-pre-dr-b04</version>
		</dependency>
		<dependency>
			<groupId>com.sun.media</groupId>
			<artifactId>clib_jiio</artifactId>
			<version>1.2-pre-dr-b04</version>
			<type>pom</type>
		</dependency>
		<dependency>
			<groupId>com.sun.media</groupId>
			<artifactId>clibwrapper_jiio</artifactId>
			<version>1.2-pre-dr-b04</version>
			<type>pom</type>
		</dependency>
		<!-- when use open-cv, set run comfigration
		-Djava.library.path="E:/Dropbox/Graphy-WorkSpace2/graphy-parent/graphy-imageio/image-io-nativelib/windows-x86-64/" -->
		<dependency>
			<groupId>org.dcm4che</groupId>
			<artifactId>dcm4che-imageio-opencv</artifactId>
			<version>${dcm4che-version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.dcm4che/dcm4che-emf -->
		<dependency>
			<groupId>org.dcm4che</groupId>
			<artifactId>dcm4che-emf</artifactId>
			<version>5.23.1</version><!-- keep this version -->
		</dependency>
		<!--
		https://mvnrepository.com/artifact/org.dcm4che.tool/dcm4che-tool-common -->
		<dependency>
			<groupId>org.dcm4che.tool</groupId>
			<artifactId>dcm4che-tool-common</artifactId>
			<version>${dcm4che-version}</version>
		</dependency>
		<!--
		https://mvnrepository.com/artifact/org.dcm4che.tool/dcm4che-tool-storescu -->
		<dependency>
			<groupId>org.dcm4che.tool</groupId>
			<artifactId>dcm4che-tool-storescu</artifactId>
			<version>${dcm4che-version}</version>
		</dependency>
		<!--
		https://mvnrepository.com/artifact/org.dcm4che.tool/dcm4che-tool-dcmqrscp -->
		<dependency>
			<groupId>org.dcm4che.tool</groupId>
			<artifactId>dcm4che-tool-dcmqrscp</artifactId>
			<version>${dcm4che-version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.dcm4che/dcm4che-net -->
		<dependency>
			<groupId>org.dcm4che</groupId>
			<artifactId>dcm4che-net</artifactId>
			<version>${dcm4che-version}</version>
		</dependency>
		<!--
		https://mvnrepository.com/artifact/org.dcm4che.tool/dcm4che-tool-dcm2xml -->
		<dependency>
			<groupId>org.dcm4che.tool</groupId>
			<artifactId>dcm4che-tool-dcm2xml</artifactId>
			<version>${dcm4che-version}</version>
		</dependency>
		<dependency>
			<groupId>org.dcm4che.tool</groupId>
			<artifactId>dcm4che-tool-dcmdir</artifactId>
			<version>${dcm4che-version}</version>
		</dependency>
		<dependency>
			<groupId>org.dcm4che.tool</groupId>
			<artifactId>dcm4che-tool-movescu</artifactId>
			<version>${dcm4che-version}</version>
		</dependency>
		<dependency>
			<groupId>org.dcm4che.tool</groupId>
			<artifactId>dcm4che-tool-getscu</artifactId>
			<version>${dcm4che-version}</version>
		</dependency>
		<dependency>
			<groupId>org.dcm4che</groupId>
			<artifactId>dcm4che-dcmr</artifactId>
			<version>${dcm4che-version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.dcm4che/dcm4che-dict -->
		<dependency>
			<groupId>org.dcm4che</groupId>
			<artifactId>dcm4che-dict</artifactId>
			<version>${dcm4che-version}</version>
		</dependency>


		<!-- MISC LIBRARIES -->
		<!-- https://mvnrepository.com/artifact/commons-io/commons-io -->
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>${apache-commons-io-version}</version>
		</dependency>

		<!--https://mvnrepository.com/artifact/org.pushing-pixels/radiance-substance -->
		<dependency>
			<groupId>org.pushing-pixels</groupId>
			<artifactId>radiance-substance</artifactId>
			<version>${radiance-substance-version}</version>
		</dependency>

		<!-- PDF -->
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>pdfbox</artifactId>
			<version>${pdfbox-version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>pdfbox-tools</artifactId>
			<version>${pdfbox-version}</version>
		</dependency>

		<dependency>
			<groupId>org.jdatepicker</groupId>
			<artifactId>jdatepicker</artifactId>
			<version>1.3.4</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.joml/joml -->
		<dependency>
			<groupId>org.joml</groupId>
			<artifactId>joml</artifactId>
			<version>${joml-version}</version>
		</dependency>
		<dependency>
			<groupId>com.github.stephenc.java-iso-tools</groupId>
			<artifactId>iso9660-writer</artifactId>
			<version>2.1.0</version>
		</dependency>
		
		<!-- https://mvnrepository.com/artifact/javax.media/jmf -->
		<dependency>
			<groupId>javax.media</groupId>
			<artifactId>jmf</artifactId>
			<version>2.1.1e</version>
		</dependency>
		<dependency>
			<groupId>org.jcodec</groupId>
			<artifactId>jcodec</artifactId>
			<version>0.2.5</version>
		</dependency>
		<dependency>
			<groupId>org.jcodec</groupId>
			<artifactId>jcodec-javase</artifactId>
			<version>0.2.5</version>
		</dependency>
		<dependency>
			<groupId>org.ow2.asm</groupId>
			<artifactId>asm</artifactId>
			<version>${asm-version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/nz.ac.waikato.cms.weka/weka-dev -->
		<dependency>
		    <groupId>nz.ac.waikato.cms.weka</groupId>
		    <artifactId>weka-dev</artifactId>
		    <version>${weka-version}</version>
		</dependency>
		<dependency>
		    <groupId>com.google.code.gson</groupId>
		    <artifactId>gson</artifactId>
		    <version>2.10.1</version>
		</dependency>
		<!-- Source: https://mvnrepository.com/artifact/ws.schild/jave-core -->
		<dependency>
		    <groupId>ws.schild</groupId>
		    <artifactId>jave-core</artifactId>
		    <version>3.5.0</version>
		    <scope>compile</scope>
		</dependency>
		<!-- Source: https://mvnrepository.com/artifact/ws.schild/jave-all-deps -->
		<dependency>
		    <groupId>ws.schild</groupId>
		    <artifactId>jave-all-deps</artifactId>
		    <version>3.5.0</version>
		    <scope>compile</scope>
		</dependency>
		<!-- 
		3D Viewer 
		LWJGL will automatically detect native libs for each platform.
		-Djava.library.path for LWJGL is not required as usual.
		-->
		<dependency>
            <groupId>org.lwjglx</groupId>
            <artifactId>lwjgl3-awt</artifactId>
            <version>0.2.3</version>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-jawt</artifactId>
            <version>${lwjgl.version}</version>
        </dependency>

        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl</artifactId><version>${lwjgl.version}</version></dependency>
        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl-opengl</artifactId><version>${lwjgl.version}</version></dependency>
        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl-glfw</artifactId><version>${lwjgl.version}</version></dependency>
        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl-assimp</artifactId><version>${lwjgl.version}</version></dependency>

        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl</artifactId><version>${lwjgl.version}</version><classifier>natives-linux</classifier><scope>runtime</scope></dependency>
        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl-opengl</artifactId><version>${lwjgl.version}</version><classifier>natives-linux</classifier><scope>runtime</scope></dependency>
        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl-glfw</artifactId><version>${lwjgl.version}</version><classifier>natives-linux</classifier><scope>runtime</scope></dependency>
        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl-assimp</artifactId><version>${lwjgl.version}</version><classifier>natives-linux</classifier><scope>runtime</scope></dependency>
        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl</artifactId><version>${lwjgl.version}</version><classifier>natives-windows</classifier><scope>runtime</scope></dependency>
        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl-opengl</artifactId><version>${lwjgl.version}</version><classifier>natives-windows</classifier><scope>runtime</scope></dependency>
        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl-glfw</artifactId><version>${lwjgl.version}</version><classifier>natives-windows</classifier><scope>runtime</scope></dependency>
        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl-assimp</artifactId><version>${lwjgl.version}</version><classifier>natives-windows</classifier><scope>runtime</scope></dependency>
        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl</artifactId><version>${lwjgl.version}</version><classifier>natives-macos</classifier><scope>runtime</scope></dependency>
        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl-opengl</artifactId><version>${lwjgl.version}</version><classifier>natives-macos</classifier><scope>runtime</scope></dependency>
        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl-glfw</artifactId><version>${lwjgl.version}</version><classifier>natives-macos</classifier><scope>runtime</scope></dependency>
        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl-assimp</artifactId><version>${lwjgl.version}</version><classifier>natives-macos</classifier><scope>runtime</scope></dependency>
        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl</artifactId><version>${lwjgl.version}</version><classifier>natives-macos-arm64</classifier><scope>runtime</scope></dependency>
        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl-opengl</artifactId><version>${lwjgl.version}</version><classifier>natives-macos-arm64</classifier><scope>runtime</scope></dependency>
        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl-glfw</artifactId><version>${lwjgl.version}</version><classifier>natives-macos-arm64</classifier><scope>runtime</scope></dependency>
        <dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl-assimp</artifactId><version>${lwjgl.version}</version><classifier>natives-macos-arm64</classifier><scope>runtime</scope></dependency>
		<!-- Source: https://mvnrepository.com/artifact/junit/junit -->
		<dependency>
		    <groupId>junit</groupId>
		    <artifactId>junit</artifactId>
		    <version>4.13.2</version>
		    <scope>test</scope>
		</dependency>
	</dependencies>
</project>