<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.vis.graphy</groupId>
  <artifactId>graphy</artifactId>
  <version>0.0.1-SNAPSHOT</version>

	<properties>
		<java.version>11</java.version>
		<maven.compiler.target>1.11</maven.compiler.target>
		<maven.compiler.source>1.11</maven.compiler.source>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		
		<imagej-version>1.54f</imagej-version>
		<dcm4che-version>5.23.2</dcm4che-version>
		<derby-version>10.14.2.0</derby-version>
		<pdfbox-version>2.0.12</pdfbox-version>
		<apache-commons-io-version>2.13.0</apache-commons-io-version>
		<radiance-substance-version>4.5.0</radiance-substance-version>
		<joml-version>1.10.5</joml-version>
	</properties>
	
	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<includes>
					<include>**/*</include>
				</includes>
				<excludes>
					<exclude>**/*test*.*</exclude>
				</excludes>
			</resource>
		</resources>
	</build>
	
	<repositories>
		<!-- pixelmed.jar -->
		<repository>
			<id>XNatLibs</id>
			<name>XNatLibs Repository</name>
			<url>https://nrgxnat.jfrog.io/artifactory/libs-release/</url>
		</repository>
		<!-- 3D_Viewer -->
		<repository>
			<id>ImageJ Releases</id>
			<name>ImageJ Releases Repository</name>
			<url>https://maven.imagej.net/content/repositories/releases/</url>
		</repository>
		<!-- dcm4che -->
		<repository>
			<id>SciJava Public</id>
			<name>SciJava Public Repository</name>
			<url>https://maven.scijava.org/content/repositories/public/</url>
		</repository>
		<repository>
			<id>Dcm4Che</id>
			<name>Dcm4Che Repository</name>
			<url>https://www.dcm4che.org/maven2/</url>
		</repository>
	</repositories>
	
	<dependencies>
		
		<!-- IMAGES LIBRARIES -->
		<!-- https://mvnrepository.com/artifact/net.imagej/ij -->
		<dependency>
		    <groupId>net.imagej</groupId>
		    <artifactId>ij</artifactId>
		    <version>${imagej-version}</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/net.imagej/ij -->
		<!--
		https://mvnrepository.com/artifact/net.ihe.gazelle.pixelmed.validator/Pixelmed-jar -->
		<!-- https://mvnrepository.com/artifact/com.dclunie/pixelmed -->
		<dependency>
			<groupId>
				com.dclunie</groupId>
			<artifactId>pixelmed</artifactId>
			<version>nrg-20200327-1</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.dclunie/pixelmed-imageio -->
		<!--
		<dependency>
		    <groupId>com.dclunie</groupId>
		    <artifactId>pixelmed-imageio</artifactId>
		    <version>20200328</version>
		</dependency>
		<dependency>
		    <groupId>com.dclunie</groupId>
		    <artifactId>pixelmed-codec</artifactId>
		    <version>20200328</version>
		</dependency>
		-->
		<dependency>
			<groupId>
				org.jogamp.gluegen</groupId>
			<artifactId>gluegen-rt-main</artifactId>
			<version>2.3.2</version>
		</dependency>
		<dependency>
			<groupId>
				org.jogamp.jogl</groupId>
			<artifactId>jogl-all-main</artifactId>
			<version>2.3.2</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/sc.fiji/3D_Viewer -->
		<dependency>
			<groupId>
				sc.fiji</groupId>
			<artifactId>3D_Viewer</artifactId>
			<version>4.0.5</version>
			<exclusions>
				<exclusion>
					<groupId>net.imagej</groupId>
					<artifactId>
						ij</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<!-- DB LIBRARIES -->

		<!-- https://mvnrepository.com/artifact/org.apache.derby/derby -->
		<dependency>
			<groupId>
				org.apache.derby</groupId>
			<artifactId>derby</artifactId>
			<version>${derby-version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.apache.derby/derbyclient -->
		<dependency>
			<groupId>
				org.apache.derby</groupId>
			<artifactId>derbyclient</artifactId>
			<version>
				${derby-version}</version>
		</dependency>

		<!-- DICOM LIBRARIES -->
		
		<dependency>
			<groupId>org.dcm4che</groupId>
			<artifactId>
				dcm4che-core</artifactId>
			<version>${dcm4che-version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.dcm4che/dcm4che-imageio-rle -->
		<dependency>
			<groupId>
				org.dcm4che</groupId>
			<artifactId>dcm4che-imageio-rle</artifactId>
			<version>
				${dcm4che-version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.dcm4che/dcm4che-imageio -->
		<dependency>
			<groupId>org.dcm4che</groupId>
			<artifactId>
				dcm4che-imageio</artifactId>
			<version>${dcm4che-version}</version>
		</dependency>
		<dependency>
			<groupId>
				com.sun.media</groupId>
			<artifactId>jai_imageio</artifactId>
			<version>1.2-pre-dr-b04</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.sun.media/clib_jiio -->
		<dependency>
		    <groupId>
				com.sun.media</groupId>
		    <artifactId>clib_jiio</artifactId>
		    <version>1.2-pre-dr-b04</version>
		    <type>
				pom</type>
		</dependency>
		<dependency>
		    <groupId>com.sun.media</groupId>
		    <artifactId>
				clibwrapper_jiio</artifactId>
		    <version>1.2-pre-dr-b04</version>
		    <type>pom</type>
		</dependency>
		<!-- when use open-cv, set run comfigration -Djava.library.path="E:/Dropbox/Graphy-WorkSpace2/graphy-parent/graphy-imageio/image-io-nativelib/windows-x86-64/" -->
		<dependency>
			<groupId>
				org.dcm4che</groupId>
			<artifactId>dcm4che-imageio-opencv</artifactId>
			<version>
				${dcm4che-version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.dcm4che/dcm4che-emf -->
		<dependency>
			<groupId>org.dcm4che</groupId>
			<artifactId>
				dcm4che-emf</artifactId>
			<version>5.23.1</version><!-- keep this version -->
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.dcm4che.tool/dcm4che-tool-common -->
		<dependency>
			<groupId>
				org.dcm4che.tool</groupId>
			<artifactId>dcm4che-tool-common</artifactId>
			<version>
				${dcm4che-version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.dcm4che.tool/dcm4che-tool-storescu -->
		<dependency>
			<groupId>
				org.dcm4che.tool</groupId>
			<artifactId>dcm4che-tool-storescu</artifactId>
			<version>
				${dcm4che-version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.dcm4che.tool/dcm4che-tool-dcmqrscp -->
		<dependency>
			<groupId>
				org.dcm4che.tool</groupId>
			<artifactId>dcm4che-tool-dcmqrscp</artifactId>
			<version>
				${dcm4che-version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.dcm4che/dcm4che-net -->
		<dependency>
			<groupId>org.dcm4che</groupId>
			<artifactId>
				dcm4che-net</artifactId>
			<version>${dcm4che-version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.dcm4che.tool/dcm4che-tool-dcm2xml -->
		<dependency>
			<groupId>
				org.dcm4che.tool</groupId>
			<artifactId>dcm4che-tool-dcm2xml</artifactId>
			<version>
				${dcm4che-version}</version>
		</dependency>
		<dependency>
			<groupId>
				org.dcm4che.tool</groupId>
			<artifactId>dcm4che-tool-dcmdir</artifactId>
			<version>
				${dcm4che-version}</version>
		</dependency>
		<dependency>
			<groupId>
				org.dcm4che.tool</groupId>
			<artifactId>dcm4che-tool-movescu</artifactId>
			<version>
				${dcm4che-version}</version>
		</dependency>
		<dependency>
			<groupId>
				org.dcm4che.tool</groupId>
			<artifactId>dcm4che-tool-getscu</artifactId>
			<version>
				${dcm4che-version}</version>
		</dependency>
		<dependency>
            <groupId>org.dcm4che</groupId>
            <artifactId>dcm4che-dcmr</artifactId>
            <version>${dcm4che-version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.dcm4che/dcm4che-dict -->
		<dependency>
		    <groupId>
				org.dcm4che</groupId>
		    <artifactId>dcm4che-dict</artifactId>
		    <version>${dcm4che-version}</version>
		</dependency>


		<!-- MISC LIBRARIES -->
		<!-- https://mvnrepository.com/artifact/commons-io/commons-io -->
		<dependency>
		    <groupId>commons-io</groupId>
		    <artifactId>commons-io</artifactId>
		    <version>${apache-commons-io-version}</version>
		</dependency>
		
		<!-- https://mvnrepository.com/artifact/org.pushing-pixels/radiance-substance -->
		<dependency>
		    <groupId>org.pushing-pixels</groupId>
		    <artifactId>radiance-substance</artifactId>
		    <version>${radiance-substance-version}</version>
		</dependency>
		
		<!-- PDF -->
		<dependency>
			<groupId>
				org.apache.pdfbox</groupId>
			<artifactId>pdfbox</artifactId>
			<version>${pdfbox-version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>pdfbox-tools</artifactId>
			<version>${pdfbox-version}</version>
		</dependency>
		
		<dependency>
			<groupId>org.jdatepicker</groupId>
			<artifactId>jdatepicker</artifactId>
			<version>1.3.4</version>
		</dependency>
		
		<!-- https://mvnrepository.com/artifact/org.joml/joml -->
		<dependency>
		    <groupId>org.joml</groupId>
		    <artifactId>joml</artifactId>
		    <version>${joml-version}</version>
		</dependency>
		<dependency>
			<groupId>com.github.stephenc.java-iso-tools</groupId>
			<artifactId>iso9660-writer</artifactId>
			<version>2.1.0</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.apache.commons/commons-math3 -->
		<dependency>
		    <groupId>org.apache.commons</groupId>
		    <artifactId>commons-math3</artifactId>
		    <version>3.6.1</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/javax.media/jmf -->
		<dependency>
		    <groupId>javax.media</groupId>
		    <artifactId>jmf</artifactId>
		    <version>2.1.1e</version>
		</dependency>
		<dependency>
			<groupId>org.jcodec</groupId>
			<artifactId>jcodec</artifactId>
			<version>0.2.5</version>
		</dependency>
		<dependency>
			<groupId>org.jcodec</groupId>
			<artifactId>jcodec-javase</artifactId>
			<version>0.2.5</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/commons-cli/commons-cli -->
		<!--
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>27.0.1-jre</version>
			<exclusions>
				<exclusion>
					<groupId>dom4j</groupId>
					<artifactId>dom4j</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		-->
		<!-- 
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.8.1</version>
		</dependency>
		-->

	</dependencies>

</project>