create table report (
	ReportID varchar(255) NOT NULL CONSTRAINT ReportID_pk PRIMARY KEY,
	Title varchar(512),
	Status varchar(32),
	ReportType varchar(32),
	Author varchar(255),
	ReferringPhysician varchar(255),
	ClinicalHistory clob,
	BodyHtml clob,
	BodyFormat varchar(16),
	KeyImageRefs clob,
	SrSopInstanceUID varchar(255),
	StudyDate date,
	CreatedDateTime timestamp,
	ModifiedDateTime timestamp,
	PredecessorReportId varchar(255),
	PredecessorSrSopUID varchar(255),
	PredecessorSeriesUID varchar(255),
	LockedBy varchar(255),
	LockedAt timestamp,
	PatientID varchar(255),
	foreign key(PatientID) references Patient(PatientID),
	StudyInstanceUID varchar(255),
	foreign key(StudyInstanceUID) references Study(StudyInstanceUID),
	SeriesInstanceUID varchar(255),
	KoSopInstanceUID varchar(255),
	KoSeriesInstanceUID varchar(255)
	)
