package com.vis.configuration;

public enum GraphyProp {
	Locale,
	GraphyDBDir,
	DICOMBackEnd,
	RoiFillColor,
	RoiStrokeColor,
	RoiStrokeWidth,
	RoiHandleColor,
	RoiBrushSize,
	RoiBrushType,
	MainScreenX,
	MainScreenDeviceID,
	LocalDBLocation,
	MainScreenHeight,
	MainScreenY,
	Viewer2DScreenDeviceID,
	MainTreeTableKeepTopTitle,
	DefaultLocalDBLocation,
	Viewer2DScreenX,
	Viewer2DScreenHeight,
	Viewer2DScreenY,
	LookAndFeels,
	RefreshQRTreeTableOn,
	Viewer2DScreenWidth,
	MainScreenWidth,
	FontSize,
	TextFont,
	UseDefaultLocalDBLocation,
	ColumnOrder;
}
