create table image (
	SOPInstanceUID varchar(255) NOT NULL CONSTRAINT SOPInstanceUID_pk PRIMARY KEY,
	SOPClassUID varchar(255),
	InstanceNumber integer,
	AcquisitionNumber varchar(128),
	multiframe boolean,
	totalframe integer,
	SendStatus varchar(50),
	AcquisitionDateTime time,
	ForwardDateTime time,
	ReceivedDateTime time,
	ReceiveStatus varchar(50),
	FileStoreUrl varchar(1000),
	isLink boolean,
	SliceLocation integer,
	EncapsulatedDocument boolean,
	ThumbnailStatus boolean,
	FrameOfReferenceUID varchar(255),
	ImagePosition varchar(64),
	ImageOrientation varchar(128),
	ImageType varchar(30),
	PixelSpacing varchar(64),
	SliceThickness varchar(16),
	Height integer,
	Width integer,
	ReferencedSOPInstanceUID varchar(255),
	TransferSyntaxUID varchar(255),
	PatientID varchar(255),
	StudyInstanceUID varchar(255),
	SeriesInstanceUID varchar(255),
	foreign key(PatientID) references Patient(PatientID),
	foreign key(StudyInstanceUID) references Study(StudyInstanceUID),
	foreign key(SeriesInstanceUID) references Series(SeriesInstanceUID)
	)
