create table roi (
	RoiID varchar(255) NOT NULL CONSTRAINT RoiID_pk PRIMARY KEY,
	Name varchar(256),
	RoiType integer,
	OriginX integer,
	OriginY integer,
	Width integer,
	Height integer,
	PointX blob,
	PointY blob,
	Shape blob,
	InstanceNo integer,
	Description varchar(256),
	RoiGroup integer,
	RoiLabel varchar(64),
	ObjectType varchar(64),
	Organ varchar(64),
	StudyDate date,
	CrossSection varchar(16),
	PatientID varchar(255),
	foreign key(PatientID) references Patient(PatientID),
	StudyInstanceUID varchar(255),
	foreign key(StudyInstanceUID) references Study(StudyInstanceUID),
	SeriesInstanceUID varchar(255),
	foreign key(SeriesInstanceUID) references Series(SeriesInstanceUID),
	SOPInstanceUID varchar(255),
	foreign key(SOPInstanceUID) references Image(SOPInstanceUID)
	)
