#overwrite Properties
#Wed Apr 21 16:35:34 JST 2021
DEVICE_CANDIDATES_0=0,0,0
WITH_VIEWER=1
SPEED=24
DEVICE_CANDIDATES_4=1,6,0
DEVICE_CANDIDATES_3=0,1,0
EJECT=1
DEVICE_CANDIDATES_2=2,0,0
DEVICE_CANDIDATES_1=1,0,0
