#overwrite Properties
#Wed Aug 28 18:43:25 JST 2024
Xmx=10g
MainScreenX=133
MainScreenDeviceID=\:0.1
LocalDBLocation=/home/tatsunidas/TEST_DB2
NumOfPadForPatientID=0
MainScreenHeight=983
MainScreenY=67
Viewer2DScreenDeviceID=\:0.0
MainTreeTableKeepTopTitle=HOME
Viewer2DScreenX=2560
Viewer2DScreenHeight=803
Viewer2DScreenY=567
LookAndFeels=javax.swing.plaf.metal.MetalLookAndFeel
RefreshQRTreeTableOn=true
FontSize=12
Viewer2DScreenWidth=1600
NO_SPLASH=false
MainScreenWidth=1920
TextFont=SansSerif.plain
UseDefaultLocalDBLocation=false
ColumnOrder=Datasets,Archived,StudyDate,PatientName,PatientID,SeriesDate,StudyTime,AquisitionTime,StudyDesc,SeriesDesc,Modality,Sex,BirthDate,Age,Institution,ModelName,SeriesNo,AcquisitionNo,InstanceNo,NumOfSeries,NumOfInstances
Xms=1g
