#overwrite Properties
#Wed Jul 24 19:01:14 JST 2024
MainScreenX=2760
MainScreenDeviceID=\:0.0
LocalDBLocation=/home/tatsunidas/.GRAPHY
NumOfPadForPatientID=0
MainScreenHeight=700
MainScreenY=640
MainTreeTableKeepTopTitle=HOME
DefaultLocalDBLocation=
LookAndFeels=javax.swing.plaf.metal.MetalLookAndFeel
RefreshQRTreeTableOn=true
FontSize=12
MainScreenWidth=1200
TextFont=12
UseDefaultLocalDBLocation=true
ColumnOrder=
