#overwrite Properties
#Tue Aug 13 18:47:16 JST 2024
Xmx=10g
MainScreenX=290
MainScreenDeviceID=\:0.1
LocalDBLocation=/home/tatsunidas/TEST_DB2
NumOfPadForPatientID=0
MainScreenHeight=978
MainScreenY=118
Viewer2DScreenDeviceID=\:0.1
MainTreeTableKeepTopTitle=HOME
Viewer2DScreenX=854
Viewer2DScreenHeight=873
Viewer2DScreenY=393
LookAndFeels=javax.swing.plaf.metal.MetalLookAndFeel
RefreshQRTreeTableOn=true
FontSize=12
Viewer2DScreenWidth=1099
NO_SPLASH=false
MainScreenWidth=1920
TextFont=SansSerif.plain
UseDefaultLocalDBLocation=false
ColumnOrder=Datasets,Archived,StudyDate,PatientName,PatientID,SeriesDate,StudyTime,AquisitionTime,StudyDesc,SeriesDesc,Modality,Sex,BirthDate,Age,Institution,ModelName,SeriesNo,AcquisitionNo,InstanceNo,NumOfSeries,NumOfInstances
Xms=1g
